name: ZenUnitAndMetalMock
on: push

jobs:
  build:
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
         cmake_build_type: [Debug, RelWithDebInfo]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('ZenUnitDevOpsPython/dev-requirements.txt') }}

      - name: Install pip packages
        run: pip install --upgrade --upgrade-strategy eager -r ZenUnitDevOpsPython/dev-requirements.txt

      - name: Run BuildAndInstallCPlusPlusProgram.py
        run: |
          python ZenUnitDevOpsPython/ZenUnitDevOpsPython/BuildAndTestZenUnitAndMetalMock.py `
            --cmake-build-type="${{ matrix.cmake_build_type }}" `
            --cmake-definitions=""
        env:
          PYTHONPATH: ZenUnitDevOpsPython

